try{
  a + b
} catch {
  console.log(222)
}
